use chrono::Utc;
use uuid::Uuid;

use crate::db::models::MemoryRecord;

/// A curated set of default memories seeded on first launch.
/// These represent universal best practices and user-facing defaults
/// that help the agent provide more relevant assistance from day one.
pub fn default_seed_memories() -> Vec<MemoryRecord> {
    let now = Utc::now().to_rfc3339();

    vec![
        // ── User Info ──
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "用户使用中文作为交流语言，Agent 回复时应优先使用中文。代码注释、变量命名、git commit 使用英文。".to_string(),
            memory_type: "user_info".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.95,
            tags: Some("language,chinese,convention".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "用户使用 Windows + PowerShell 作为开发环境。文件路径使用反斜杠，但推荐在代码中使用正斜杠以保证跨平台兼容。".to_string(),
            memory_type: "user_info".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.90,
            tags: Some("platform,windows,powershell".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },

        // ── Preferences ──
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "代码质量优先于开发速度。优先考虑可维护性、可读性和正确性。避免使用 'as any'、'@ts-ignore' 等类型逃逸手段。".to_string(),
            memory_type: "preference".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.95,
            tags: Some("code-quality,type-safety,best-practice".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "提交代码前需要验证：运行 LSP diagnostics 确保没有错误，运行测试确保不破坏现有功能。修改后不需要主动 commit，除非用户明确要求。".to_string(),
            memory_type: "preference".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.85,
            tags: Some("workflow,verification,testing".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "修复 Bug 时最小化修改范围，只修复问题本身，不要同时重构代码。重构和修复应该分开进行。".to_string(),
            memory_type: "preference".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.88,
            tags: Some("bugfix,refactoring,best-practice".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "优先使用现有库和工具，避免引入新的依赖。如果必须引入新依赖，优先选择活跃维护、社区广泛使用的库。".to_string(),
            memory_type: "preference".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.82,
            tags: Some("dependencies,best-practice".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "对复杂任务先制定计划再实施。多步骤任务先创建 TODO 列表分解步骤，每完成一步标记完成。避免一次性做大量修改。".to_string(),
            memory_type: "preference".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.85,
            tags: Some("workflow,planning,organization".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "当不确定用户意图或方案有多个合理选择时，先向用户澄清再行动。不要猜测。提供选项和推荐方案供用户选择。".to_string(),
            memory_type: "preference".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.80,
            tags: Some("communication,clarification".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },

        // ── Facts (通用开发知识) ──
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "Rust 项目使用 cargo check 快速验证编译，比 cargo build 更快。cargo test 运行测试。rustfmt 用于格式化代码。".to_string(),
            memory_type: "fact".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.75,
            tags: Some("rust,cargo,toolchain".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "Tauri 项目结构：src-tauri/ 是 Rust 后端，src-ui/ 是 React + TypeScript 前端。构建桌面应用使用 cargo tauri build，前端开发服务器使用 npm run dev。".to_string(),
            memory_type: "fact".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.70,
            tags: Some("tauri,project-structure,desktop".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "良好的 commit message 格式：使用 conventional commits（feat/fix/refactor/chore/docs/test），第一行不超过 72 字符，正文解释为什么和怎么做。".to_string(),
            memory_type: "fact".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.72,
            tags: Some("git,commit,convention".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "Tauri 的 CSP 配置在 tauri.conf.json 中，新增 LLM provider 或 API base URL 时需要同步更新 connect-src 白名单，否则请求会被阻止。".to_string(),
            memory_type: "fact".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.78,
            tags: Some("tauri,csp,security,provider".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "TypeScript 严格模式下 noUnusedLocals 和 noUnusedParameters 均开启——未使用的参数前加 _ 前缀以避免编译错误。".to_string(),
            memory_type: "fact".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.76,
            tags: Some("typescript,compiler-options,convention".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "前端使用单一 Zustand 仓库管理状态，所有状态和异步 IPC 封装在 store/index.ts 中。使用 TailwindCSS 样式系统，自定义紫色 primary 调色板。".to_string(),
            memory_type: "fact".to_string(),
            scope: "global".to_string(),
            source: "builtin".to_string(),
            relevance: 0.74,
            tags: Some("frontend,zustand,tailwindcss,state".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },

        // ── Project Context ──
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "当前项目 Agent 是一个 Tauri 桌面 AI 客户端，支持多 LLM 后端（OpenAI、Anthropic 等 11 个 provider），具备 Agent 循环、MCP 服务器管理、技能系统、工作流引擎、运行时环境管理等功能。".to_string(),
            memory_type: "project_context".to_string(),
            scope: "project:agent".to_string(),
            source: "builtin".to_string(),
            relevance: 0.85,
            tags: Some("project,agent,overview".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "Agent 项目的工具系统支持：calculator（计算器）、file_system（文件操作）、web_search（网络搜索）、code_executor（代码执行）、script_tool（脚本工具）。新工具通过实现 Tool trait 并注册到 ToolRegistry 添加。".to_string(),
            memory_type: "project_context".to_string(),
            scope: "project:agent".to_string(),
            source: "builtin".to_string(),
            relevance: 0.82,
            tags: Some("project,tools,agent".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
        MemoryRecord {
            id: Uuid::new_v4().to_string(),
            content: "MCP（Model Context Protocol）是 Agent 连接外部工具的标准协议。支持多个 MCP 服务器同时连接，每个服务器的工具可以单独配置启用/禁用、确认模式（auto_allow/confirm_once/deny）。".to_string(),
            memory_type: "project_context".to_string(),
            scope: "project:agent".to_string(),
            source: "builtin".to_string(),
            relevance: 0.80,
            tags: Some("project,mcp,protocol".to_string()),
            created_at: now.clone(),
            updated_at: now.clone(),
            last_accessed_at: now.clone(),
            access_count: 0,
        },
    ]
}
